server:
  port: 8888
spring:
  application:
    name: hotelity-backend
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(6VSddndzXr0YDHJYyT64VCk3YJIrckuloDLP0YireJqq7LOyuOoirsY3ZOlCkyDCr3hfJZBkYK/yxylrm+Xw20hCg5ISJ3lMfgvol0bCwlbV9gOLrETo091LEIZ/Tppx3vhP2CUQYWg=)
    username: ENC(pp8u3oidFVpc67XmKnwo7g==)
    password: ENC(DoalWPPUKYQ3TVK+I6ikUolT4CQI5zz1)
    hikari:
      maximumPoolSize: 15
      minimumIdle: 5
      idleTimeout: 10000
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      #      host: 192.168.0.31
      host: localhost
      port: 6379
      expiration_time: 86400000 # 1일
  mail:
    host: ENC(X0lp60VwcpA3UfhpJoQVfh2d9U4YAq4P)
    port: 587
    username: ENC(UpWAZf2E9rPGbAWQJHVtxSHuJgq0bMbmRBOP9301itY=)
    password: ENC(Ucb9XqM3XXTGqCCMoj8V2Ug5RiFF4DUr4TcwImCzJ6U=)
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          auth: false

token:
  expiration_time: 3600000 # 1시간
  secret: ENC(9zH/P4wC1GCUSj5EXoQogcwXf7zaU+PnWqO6AM5Dr+NuMX3KB9cgJ0u9b874/weSKWjRe/ghbHmo8cCiFWj+R7JnEput0uhYRAVyxHxJ0kkN8lH3sMZvWflfimVI6LkGj+B0AtzL3MM=)

aws:
  s3:
    accessKey: ENC(v8DtB1meCEW7SybjNkXVotzPa+SJdPbZl37mMDL94tc=)
    secretKey: ENC(pMI7I7holnLzpBYVfIJA4LBFvoqKsHMhPI1ixgouYt8I7aVmGnFtqWJBASghj3OThsJ54Hv8qBU=)
    bucket: ENC(krXdCMxTE3aP2ecofK/QXkOb0K3OXSxa)