spring:
  application:
    name: hotelity-backend
  profiles:
    active: dev
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ${{ secrets.HOTELITY_DB_URL }}
      username: ${{ secrets.HOTELITY_DB_USERNAME }}
      password: ${{ secrets.HOTELITY_DB_PASSWORD }}
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      #      host: 192.168.0.31
      host: localhost
      port: 6379
      expiration_time: 86400000 # 1일
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${{ secrets.HOTELITY_MAIL_USERNAME }}
    password: ${{ secrets.HOTELITY_MAIL_PASSWORD }}
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          auth: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

token:
  expiration_time: 3600000 # 1시간
  secret: ${{ secrets.HOTELITY_SECRET_KEY }}

aws:
  s3:
    accessKey: ${{ secrets.HOTELITY_AWS_ACCESS_KEY }}
    secretKey: ${{ secrets.HOTELITY_AWS_SECRET_KEY }}
    bucket: ${{ secrets.HOTELITY_AWS_BUCKET }}
server:
  port: 8888