apiVersion: v1
kind: Service
metadata:
  name: hotelity-backend-ser
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8888
      protocol: TCP
      nodePort: 30001
  selector:
    app: hotelity-backend